### PR TITLE
LL-7962 - Sidebar fixes, theme and layout, always display toggle

### PR DESCRIPTION
**Pull request by nparigi-ledger**
[LL-7962]

[LL-7962]: https://ledgerhq.atlassian.net/browse/LL-7962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by qd-qd — COMMENTED** [review]
Have we decided to always display the switch button? 🤔

**Comment by nparigi-ledger** [comment]
> Have we decided to always display the switch button? thinking

https://ledgerhq.atlassian.net/browse/LL-7962

> The collapse button only appears when the menu itself is hovered and not the button, this makes it frustrating to click it sometimes
Wasn't that what it implicitly meant ? I may have greatly misunderstood the ticket :smiley: 
Is it really about being able to hover the 16px half of the hidden button ?
Can we have some clarifications about this ticket @LFBarreto ?

**Comment by LFBarreto** [comment]
@nicolas-ledger i think you can have an animation of fade in-out with the :focus-within selector to show the button on hover on the sidebar or the button :thinking:

**Comment by nparigi-ledger** [comment]
@qd-qd @LFBarreto I have put the toggle fade out on mouse leave again, but i added a transparent div to increase the mouse zone on the left on the sidebar as recommanded by @LFBarreto

**Pull request merged**
